# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdd():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_add(self):
    self.driver.get("http://127.0.0.1:2000/addcategories")
    self.driver.set_window_size(808, 816)
    self.driver.find_element(By.NAME, "categories").click()
    self.driver.find_element(By.NAME, "categories").send_keys("UPS")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container:nth-child(15) .card-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container:nth-child(15) .card-title").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".container:nth-child(15) .card-title")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".container:nth-child(15) .card-title")
    assert len(elements) > 0
  
